version: "3.9"
services:
  db:
    image: postgres:15
    env_file: .env
    ports:
      - "5434:5432"
  web:
    build: .
    depends_on:
      - db
    restart: always
    env_file: .env
    ports:
      - "8000:80"
